### PR TITLE
Take-home Ops project

### PR DESCRIPTION
**Pull request by stackptr**
The exercise is roughly:

1. Dockerize `meatbar`
2. Push images to ECR or Heroku
3. Set up ECS in AWS console to point to image
4. Deploy within a 2-instance ECS fargate cluster via CloudFormation
5. Use platform-cli instead of CloudFormation

### CODE REVIEW

**Comment by stackptr** [comment]
Notes for the first step of this project:

- With the current `Dockerfile`, `docker build -t meatbar .` takes several minutes to `stack build`, which might be due to packages used in the `stack.yaml` resolver `lts-16.24` not being present in the `haskell:8.8.4` base image. I see there is an alternate [`fpco/stack-build`](https://hub.docker.com/r/fpco/stack-build/) base image specifically for stack, but it does not seem to have the the `lts-16.24` that this project uses, looking in the [stackage repo](https://github.com/commercialhaskell/stackage/tree/master/automated/dockerfiles).
- Developing the `Dockerfile`, I noticed that if there was a `COPY . .` instruction at the top it would invalidate the cache seemingly whenever the `Dockerfile` itself changes. As a result, I wanted to copy the requisite files from the context to the working directory to do the `stack build`, and _then_ do the overall `COPY` so that only changes to files that would affect the `build` would necessitate another one. Couldn't really find an elegant way to copy both directories and files at once, because it seems `COPY ["app", "stack.yaml", "."]` will not actually create an `app` directory in the destination, but will instead copy the _contents_ of `app/` into `.`.
- When running the image via `docker run -p 8080:8080 meatbar`, the final `stack run` does not output anything after completing to indicate that the server is ready and can receive connections. Until trying on `localhost`, this looked like the image was hanging.
- Adding `docker-compose.yml` in 751e1dc had the curious effect of failing on an instruction that had previously passed when building the images without a compose. I'm not sure why this would happen:
```
Step 6/11 : COPY ["README.md", "stack.yaml", "package.yaml", "."]
ERROR: Service 'meatbar' failed to build : When using COPY with more than one source file, the destination must be a directory and end with a /
```

The next step is to do the AWS parts, unclear how much of that work will involve changes to this project.

**Comment by pbrisbin** [comment]
>  I see there is an alternate fpco/stack-build base image specifically for stack, but it does not seem to have the the lts-16.24

I like to use the `fpco/stack-build` image, but you are correct that the resolver tag and your desired tag should align. There's no real reason this project uses the LTS it does, so we could change it. In our real Apps we want to use "latest". However, we are also starting to maintain our own [Haskell build image](https://github.com/freckle/images) to solve this. We would just ensure we have them available at the resolver(s) we need.

> I noticed that if there was a COPY . . instruction at the top it would invalidate the cache seemingly whenever the Dockerfile itself changes

When `COPY . .` does too much, the first thing to check is `.dockerignore`. It should exclude anything not necessary in the build image outright, so any `COPY` anywhere won't spend time on those files. Use of `COPY .` is very convenient, but is most impacted when `.dockerignore` is forgotten. Adding `Dockerfile` to `.dockerignore` is common.

> As a result, I wanted to copy the requisite files from the context to the working directory to do the stack build, and then do the overall COPY so that only changes to files that would affect the build would necessitate another one.

Your approach to layering is spot-on -- but it's also a Haskell-specific thing, so this is an area where the "ops" homework is impacted by understanding the deployed application language, so we don't ding the candidates for missing it. For your reference, the current best practice is something like:



```dockerfile
FROM {hefty build image} AS builder

RUN mkdir -p src
WORKDIR src

# Only changes to these files will bust the dependencies layer cache
COPY stack.yaml package.yaml x.cabal .
RUN stack install --dependencies-only

# Normal application changes pick up from here and only re-build application-level code
COPY src ./src
COPY app ./app
RUN stack install

FROM {slim runtime image}
COPY --from=builder /root/.local/bin/exe ...
```

> Couldn't really find an elegant way to copy both directories and files at once, because it seems COPY ["app", "stack.yaml", "."] will not actually create an app directory in the destination, but will instead copy the contents of app/ into ..

Yeah, I hate this behavior too. You'll see my `COPY src ./src` above to get around it.

> the final stack run does not output anything

Good note, we should fix that.

> the curious effect of failing on an instruction that had previously passed when building the images without a compose. I'm not sure why this would happ

That commit shows more diff, which is actually the issue:

**Comment by pbrisbin** [comment]
Oh, ignore my last comment. I see now that was you _fixing_ the error. I can't explain why it cropped up when it did.

**Comment by stackptr** [comment]
> Adding `Dockerfile` to `.dockerignore` is common.

Ah, this makes sense. The approach in the example `Dockerfile` makes sense: copy files that define dependencies, install dependencies, copy application code, build application code. I wonder about the use of multiple images in the case where the "slim image" seems to just be defining the entrypoint? I don't see the utility in that until there is a good amount of bootstrap logic that needs to run.

Good to know about the [freckle/images](https://github.com/freckle/images) repo!

**Comment by stackptr** [comment]
Tried to deploy to Heroku:
- Signed up a personal account
- `heroku login`
- `heroku container:login`
- `heroku container:push meatbar -a meatbar`

This push seemed to stall after a minute. I'm not sure if it is throttling on Heroku's end (one of the image layers, presumably containing the `stack build` is 1.317 GB) or what.

Trying instead to push to ECR:
- `aws configure` (using my personal AWS because I believe I lack permissions for Freckle ECR)
- `aws ecr get-login-password ... | docker login ...`
- `docker tag meatbar:latest ecr.region.amazonaws.com/meatbar:latest`
- `docker push ecr.region.amazonaws.com/meatbar:latest`

Same thing, pushing is very slow. I think the image layer size should be a red flag that I'm doing something wrong. Checking in Freckle ECR, `frontrow/fancy-api` is ~230 MB and `frontrow/base` ~38 MB. `docker-backend` or other CI jobs that entail building the images do not take longer than a minute or two to push.

Shell informs me that waiting for this push took 23 minutes.

**Comment by stackptr** [comment]
Surprisingly, the large image layer doesn't seem to be coming from the `Dockerfile` I've written but instead is in the base image, `haskell:8.8.4`. The 1.32 GB layer seems to be from this [RUN command](https://github.com/haskell/docker-haskell/blob/fb5c774c38a7ab2e7d233d95368be0f899353496/8.8/buster/Dockerfile#L16-L35).
```
❯ docker history meatbar
IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
d4940e15e50f   6 days ago    CMD ["run"]                                     0B        buildkit.dockerfile.v0
<missing>      6 days ago    ENTRYPOINT ["stack"]                            0B        buildkit.dockerfile.v0
<missing>      6 days ago    EXPOSE map[8080/tcp:{}]                         0B        buildkit.dockerfile.v0
<missing>      6 days ago    COPY . . # buildkit                             17.6MB    buildkit.dockerfile.v0
<missing>      6 days ago    RUN stack build # buildkit                      376MB     buildkit.dockerfile.v0
<missing>      6 days ago    COPY README.md stack.yaml package.yaml . # b…   1.33kB    buildkit.dockerfile.v0
<missing>      6 days ago    COPY webapp ./webapp # buildkit                 595kB     buildkit.dockerfile.v0
<missing>      6 days ago    COPY src ./src # buildkit                       2.3kB     buildkit.dockerfile.v0
<missing>      6 days ago    COPY app ./app # buildkit                       657B      buildkit.dockerfile.v0
<missing>      6 days ago    WORKDIR /opt/meatbar                            0B        buildkit.dockerfile.v0
<missing>      4 weeks ago   /bin/sh -c #(nop)  CMD ["ghci"]                 0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  ENV PATH=/root/.cabal/bin…   0B        
<missing>      4 weeks ago   |6 CABAL_INSTALL=3.2 DEBIAN_KEY=427CB69AAC9D…   63.2MB    
<missing>      4 weeks ago   |6 CABAL_INSTALL=3.2 DEBIAN_KEY=427CB69AAC9D…   1.32GB    
<missing>      4 weeks ago   /bin/sh -c #(nop)  ARG STACK_RELEASE_KEY=2C6…   0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  ARG STACK_KEY=C5705533DA4…   0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  ARG STACK=2.5.1              0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  ARG CABAL_INSTALL=3.2        0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  ARG DEBIAN_KEY=427CB69AAC…   0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  ARG GHC=8.8.4                0B        
<missing>      4 weeks ago   /bin/sh -c apt-get update &&     apt-get ins…   25.3MB    
<missing>      4 weeks ago   /bin/sh -c #(nop)  ENV LANG=C.UTF-8             0B        
<missing>      4 weeks ago   /bin/sh -c #(nop)  CMD ["bash"]                 0B        
<missing>      4 weeks ago   /bin/sh -c #(nop) ADD file:8f75f11b2bd2d50e5…   114MB     
```

In ECR, `meatbar:latest` is 425 MB. Still seems to be large, but possibly the very long initial upload is conventional, and future pushes will be quicker.

**Comment by stackptr** [comment]
I moved stuff in the `Dockerfile` to better layer on dependencies and then app code. I remember I had tried this approach originally, but saw this during `docker build` that I thought indicated I had done something wrong. This doesn't fail the build however. I wonder if it is normal to ignore the warnings around a manifest when building these image layers, and instead perform some manifest check at the end of the build.

```
 => [ 4/10] RUN ["stack", "install", "--dependencies-only"]                                                                                               9.4s
 => => # Specified pattern "webapp/*.js" for data-files does not match any files                                                                              
 => => # Specified pattern "webapp/*.json" for data-files does not match any files                                                                            
 => => # Specified pattern "webapp/*.png" for data-files does not match any files                                                                             
 => => # Specified pattern "webapp/*.ico" for data-files does not match any files                                                                             
 => => # Specified source-dir "app" does not exist                                                                                                            
 => => # Specified source-dir "src" does not exist                                                                                                            
```

**Comment by stackptr** [comment]
In order to push the changes in `Dockerfile`, I had to run `docker tag` again (or perhaps it was running `docker-compose up`). Otherwise the `docker push` found all the layers already existing. Pushing this time took a little over a minute, so that's good.

**Comment by stackptr** [comment]
Referring to this [guide](https://towardsdatascience.com/deploying-web-applications-with-docker-in-aws-fargate-bb942de733a4) to try to understand the interplay between ECS, Fargate, and Cloud Formation. I copied the [gist](https://gist.githubusercontent.com/vioquedu/d98f9f4a9dcb6e41ae37827c7e38e1e1/raw/89fb6fc30daee8d5f9fa34aff1cbe473fb564d36/aws-docker-fargate.json) and have been updating it to get the Cloud Formation stack to start.

Currently, the ECS service is unable to start due to role permissions problems:

```
service Service-CF failed to launch a task with (error ECS was unable to assume the role 'arn:aws:iam::299740371597:role/ecsTaskExecutionRole' that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role.).
```

A bit odd given that I went I find the role in IAM, it seems supplied as part of the service and I'm not able to change it. This [StackOverflow](https://stackoverflow.com/questions/48997463/ecs-unable-to-assume-role) suggests adding `ecs-tasks.amazonaws.com` to the "trust policy" but as yet I've been unable to figure out how to modify it.

**Comment by pbrisbin** [comment]
>  I wonder about the use of multiple images in the case where the "slim image" seems to just be defining the entrypoint? I don't see the utility in that until there is a good amount of bootstrap logic that needs to run.

The fact that the second stage does almost nothing is exactly the point. None of the data in the layers of the first stage will be present in the final image, making it much smaller.

> Surprisingly, the large image layer doesn't seem to be coming from the Dockerfile I've written but instead is in the base image, haskell:8.8.4. The 1.32 GB layer seems to be from this RUN command.

That's exactly right. The pattern with mult-stage builds is that the first stage has all the compiler tooling, all the dependency code; it'll be **huge**. But none of that will end up in the final image when you make a second stage that just copies the binary across. By not doing multi-stage, you're effectively deploying GHC along with your app :grimacing: 

> I thought indicated I had done something wrong. This doesn't fail the build however. I wonder if it is normal to ignore the warnings around a manifest when building these image layers

Yeah, sorry I didn't warn you. It's just an effect of the approach. You don't want those files there for that step (or they'll bust its cache), so you have to accept the warning that they're not there. It all should still work fine -- and no need for any kind of "perform some manifest check at the end", IMO.

That IAM error is strange, and I'm not sure what's going on. I would honestly go back to the Heroku route. "Bare metal" CloudFormation can be full of these little side-quests, that aren't particularly valuable for the day job. In a real Freckle App, you'd hopefully use Platform, which has wrestled away those problems already.

- https://renaissancelearning.atlassian.net/wiki/spaces/ARCH/pages/1377173841/Freckle+Platform#Installation-&-Usage
- https://renaissancelearning.atlassian.net/wiki/spaces/ARCH/pages/1377337853/Deploying+a+Web+App+on+Freckle+Platform

That said, if you want to learn CFN for CFN's sake I'm down and happy to help -- might need to dig in more synchronously.

**Pull request closed without merging**
